branch-defaults:
  default:
    environment: PetMeNow-dev
    group_suffix: null
global:
  application_name: PetMeNow
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 17 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  deploy:
    artifact: target/petmenow-0.0.1-SNAPSHOT.jar
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
