INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Retrievers (Labrador)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'French Bulldogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'German Shepherd Dogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Retrievers (Golden)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Bulldogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Poodles');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Beagles');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Rottweilers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Pointers (German Shorthaired)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Dachshunds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Pembroke Welsh Corgis');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Australian Shepherds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Yorkshire Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Boxers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Great Danes');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Siberian Huskies');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Cavalier King Charles Spaniels');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Doberman Pinschers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Miniature Schnauzers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Shih Tzu');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Boston Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Bernese Mountain Dogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Pomeranians');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Havanese');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Cane Corso');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Spaniels (English Springer)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Shetland Sheepdogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Brittanys');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Pugs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Spaniels (Cocker)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Miniature American Shepherds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Border Collies');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Mastiffs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Chihuahuas');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Vizslas');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Basset Hounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Belgian Malinois');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Maltese');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Weimaraners');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Collies');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Newfoundlands');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Rhodesian Ridgebacks');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Shiba Inu');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'West Highland White Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Bichons Frises');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Bloodhounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Spaniels (English Cocker)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Akitas');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Portuguese Water Dogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Retrievers (Chesapeake Bay)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Dalmatians');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'St. Bernards');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Papillons');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Australian Cattle Dogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Bullmastiffs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Samoyeds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Scottish Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Soft Coated Wheaten Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Whippets');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Pointers (German Wirehaired)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Chinese Shar-Pei');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Airedale Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Wirehaired Pointing Griffons');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Bull Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Alaskan Malamutes');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Cardigan Welsh Corgis');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Giant Schnauzers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Old English Sheepdogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Italian Greyhounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Great Pyrenees');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Dogues de Bordeaux');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Russell Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Cairn Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Irish Wolfhounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Setters (Irish)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Greater Swiss Mountain Dogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Miniature Pinschers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Lhasa Apsos');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Chinese Crested');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Coton de Tulear');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Staffordshire Bull Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'American Staffordshire Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Rat Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Chow Chows');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Anatolian Shepherd Dogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Basenjis');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Spaniels (Boykin)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Lagotti Romagnoli');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Brussels Griffons');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Retrievers (Nova Scotia Duck Tolling)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Norwegian Elkhounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Standard Schnauzers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Dogo Argentinos');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Bouviers des Flandres');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Pekingese');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Keeshonden');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Border Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Leonbergers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Tibetan Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Neapolitan Mastiffs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Setters (English)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Retrievers (Flat-Coated)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Borzois');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Fox Terriers (Wire)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Miniature Bull Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Belgian Tervuren');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Setters (Gordon)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Silky Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Norwich Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Spinoni Italiani');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Japanese Chin');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Welsh Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Toy Fox Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Schipperkes');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Parson Russell Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Pointers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Belgian Sheepdogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Tibetan Spaniels');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'American Eskimo Dogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Irish Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Beaucerons');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Afghan Hounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Boerboels');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Fox Terriers (Smooth)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Bearded Collies');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Black Russian Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Black and Tan Coonhounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Spaniels (Welsh Springer)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'American Hairless Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Norfolk Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Xoloitzcuintli');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Manchester Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Kerry Blue Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Australian Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Spaniels (Clumber)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Lakeland Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Bluetick Coonhounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'English Toy Spaniels');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'German Pinschers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Tibetan Mastiffs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Bedlington Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Greyhounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Pulik');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Salukis');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Barbets');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Redbone Coonhounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Swedish Vallhunds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Sealyham Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Spanish Water Dogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Briards');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Berger Picards');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Entlebucher Mountain Dogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Treeing Walker Coonhounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Icelandic Sheepdogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Wirehaired Vizslas');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Pumik');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Portuguese Podengo Pequenos');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Spaniels (American Water)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Retrievers (Curly-Coated)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Spaniels (Field)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Lowchen');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Nederlandse Kooikerhondjes');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Affenpinschers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Petits Bassets Griffons Vendeens');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Finnish Lapphunds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Scottish Deerhounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Plott Hounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Norwegian Buhunds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Glen of Imaal Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Setters (Irish Red and White)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Ibizan Hounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Spaniels (Sussex)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Bergamasco Sheepdogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Spaniels (Irish Water)');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Polish Lowland Sheepdogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Otterhounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Kuvaszok');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Komondorok');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Cirnechi dell’Etna');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Pharaoh Hounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Dandie Dinmont Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Pyrenean Shepherds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Skye Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Canaan Dogs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'American English Coonhounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Chinooks');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Finnish Spitz');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Grand Basset Griffon Vendeens');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Sloughis');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Harriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Cesky Terriers');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'American Foxhounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Azawakhs');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'English Foxhounds');
INSERT INTO petmenowDB.pet_breed_master(pet_type_id,pet_breed) VALUES(1,'Norwegian Lundehunds');